DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS ORDERS;

CREATE TABLE IF NOT EXISTS ADDRESS (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  COUNTRY VARCHAR(50) NOT NULL,
  CITY VARCHAR(50) NOT NULL,
  STREET VARCHAR(50) NOT NULL,
  HOME VARCHAR(50) NOT NULL,
  APARTMENT VARCHAR(50) NOT NULL,
  CONSTRAINT PK_ADDRESS PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS CATEGORY (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  CONSTRAINT PK_CATEGORY PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS USER (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  LOGIN VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(45) NOT NULL,
  FIRSTNAME VARCHAR(45) NOT NULL,
  LASTNAME VARCHAR(45) NOT NULL,
  PHOTO VARCHAR(45) DEFAULT NULL,
  CASH INT(11) NOT NULL DEFAULT '0',
  RATING INT(11) NOT NULL DEFAULT '0',
  ROLE VARCHAR(10) NOT NULL DEFAULT 'USER' IN ('ADMIN','USER'),
  STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' IN ('ACTIVE','INACTIVE') ,
  CONSTRAINT PK_USER PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS PRODUCT (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_ID INT(11) DEFAULT NULL,
  CATEGORY_ID INT(11) DEFAULT NULL,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(50) NOT NULL,
  COST INT(11) NOT NULL,
  DISCOUNT INT(11) NOT NULL,
  COUNT INT(11) NOT NULL,
  RATING INT(11) NOT NULL,
  STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' IN ('ACTIVE','INACTIVE'),
  CONSTRAINT PK_PRODUCT PRIMARY KEY (ID),
  CONSTRAINT FK_PRODUCT_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);
CREATE TABLE IF NOT EXISTS ORDERS (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  USER_ID INT(11) NOT NULL,
  PRODUCT_ID INT(11) NOT NULL,
  ADDRESS_ID INT(11) NOT NULL,
  BUYING_DATE DATE DEFAULT NULL,
  DELIVERY_DATE DATE DEFAULT NULL,
  STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' IN ('ACTIVE','INACTIVE'),
  CONSTRAINT PK_ORDERS PRIMARY KEY (ID),
  CONSTRAINT FK_ORDERS_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_ORDERS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
  CONSTRAINT FK_ORDERS_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID)
);

INSERT INTO ADDRESS(ID, COUNTRY, CITY, STREET, HOME, APARTMENT)
VALUES(1, 'england', 'london', 'power', '177', '666');

INSERT INTO CATEGORY(ID, NAME)
VALUES(1, 'soft');
INSERT INTO CATEGORY(ID, NAME)
VALUES(2, 'phones');

INSERT INTO USER(ID, LOGIN, PASSWORD, FIRSTNAME, LASTNAME, PHOTO, CASH, RATING, ROLE, STATUS)
VALUES (1, 'rel', '123', 'rel', 'mayer', null, 0, 0, 'ADMIN', 'ACTIVE');
INSERT INTO USER(ID, LOGIN, PASSWORD, FIRSTNAME, LASTNAME, PHOTO, CASH, RATING, ROLE, STATUS)
VALUES (2, 'lil', '123', 'lil', 'torn', null, 0, 0, 'USER', 'ACTIVE');
INSERT INTO USER(ID, LOGIN, PASSWORD, FIRSTNAME, LASTNAME, PHOTO, CASH, RATING, ROLE, STATUS)
VALUES (3, 'mel', '123', 'melissa', 'tox', null, 0, 0, 'USER', 'INACTIVE');

INSERT INTO PRODUCT(ID, USER_ID, CATEGORY_ID, NAME, DESCRIPTION, COST, DISCOUNT, COUNT, RATING, STATUS)
VALUES (1, 2, 1, 'osx1', 'win', 100, 0, 1, 0, 'ACTIVE');
INSERT INTO PRODUCT(ID, USER_ID, CATEGORY_ID, NAME, DESCRIPTION, COST, DISCOUNT, COUNT, RATING, STATUS)
VALUES (2, 2, 1, 'osx5', 'win', 100, 0, 1, 1, 'ACTIVE');
INSERT INTO PRODUCT(ID, USER_ID, CATEGORY_ID, NAME, DESCRIPTION, COST, DISCOUNT, COUNT, RATING, STATUS)
VALUES (3, 2, 1, 'osx3', 'win', 100, 50, 1, 2, 'ACTIVE');

INSERT INTO ORDERS(ID, USER_ID, PRODUCT_ID, ADDRESS_ID, BUYING_DATE, DELIVERY_DATE, STATUS)
VALUES(1, 3, 1, 1, '2018-06-04', '2018-06-04', 'ACTIVE');
INSERT INTO ORDERS(ID, USER_ID, PRODUCT_ID, ADDRESS_ID, BUYING_DATE, DELIVERY_DATE, STATUS)
VALUES(17, 2, 2, 1, null, null, 'ACTIVE');
INSERT INTO ORDERS(ID, USER_ID, PRODUCT_ID, ADDRESS_ID, BUYING_DATE, DELIVERY_DATE, STATUS)
VALUES (20, 2, 2, 1, null, null, 'ACTIVE');
INSERT INTO ORDERS(ID, USER_ID, PRODUCT_ID, ADDRESS_ID, BUYING_DATE, DELIVERY_DATE, STATUS)
VALUES (21, 2, 3, 1, null, null, 'ACTIVE');
